Checks that docker is installed
The current error when docker is missing is not very helpful:

 ERROR: Operation failed, aborting dox.

The debug one doesn't help more, this change start 'docker version'
command earlier to have a clear error message.

Change-Id: I1e6ac247b0a619915600f604d5f316d5f053e8c1