More informative error when command fails
Instead of:

    ERROR|dox.cmd|Operation failed, aborting dox.

we get:

    ERROR|dox.cmd|Operation failed, aborting dox.
    Traceback (most recent call last):
      File "/Users/marca/dev/git-repos/dox/dox/cmd.py", line 99, in run_dox
        map(run, images)
      File "/Users/marca/dev/git-repos/dox/dox/runner.py", line 209, in run
        self.build_test_image(image, command)
      File "/Users/marca/dev/git-repos/dox/dox/runner.py", line 157, in build_test_image
        shutil.copy(add_file, os.path.join(tempd, add_file))
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 119, in copy
        copyfile(src, dst)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 82, in copyfile
        with open(src, 'rb') as fsrc:
    IOError: [Errno 2] No such file or directory: 'tests_require.txt'

Change-Id: Icdb25ae2c2f06ffab416d215a7f8b360f9b65c1e